baseurl = "https://datafordemocracy.github.io/"
title = "Data for Democracy Lab"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Michele Claibourn"
disqusShortname = ""
googleAnalytics = ""
publishDir = "../datafordemocracy.github.io"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[Author]
    name = "Data for Democracy @ UVA"
    profile = "https://www.sites.google.com/site/mclaibourn/home"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Data for Democracy @ UVA"
    description = "Data Science in the Public Interest"
    github = "https://github.com/datafordemocracy"
    email = "mclaibourn@virginia.edu"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    project = "/:filename/"
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 3
